# Generated by Django 4.1.3 on 2022-11-16 11:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hosp',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('single', models.IntegerField(blank=True, default=1)),
                ('double', models.IntegerField(blank=True, default=1)),
                ('triple', models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='patientdata',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('hospital', models.CharField(max_length=30)),
                ('disease', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('Primary', 'Primary Checkup'), ('Admitted', 'Admitted'), ('Discharged', 'Discharged')], default='Primary', max_length=20)),
                ('allergies', models.CharField(blank=True, max_length=50)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('room', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital.hosp')),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('hospital', models.CharField(max_length=30)),
                ('disease', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('Primary', 'Primary Checkup'), ('Admitted', 'Admitted'), ('Discharged', 'Discharged')], default='Primary', max_length=20)),
                ('allergies', models.CharField(blank=True, max_length=50)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('room', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital.hosp')),
            ],
        ),
    ]
