# Generated by Django 4.1.3 on 2022-11-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_patient_id_patient_allergies_patient_disease_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single', models.IntegerField(default=1)),
                ('double', models.IntegerField(default=1)),
                ('triple', models.IntegerField(default=1)),
            ],
        ),
    ]
