# Generated by Django 4.1.3 on 2022-11-14 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_rooms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rooms',
        ),
    ]
