# Generated by Django 4.1.3 on 2022-11-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_delete_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='hosp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single', models.IntegerField(default=1)),
                ('double', models.IntegerField(default=1)),
                ('triple', models.IntegerField(default=1)),
            ],
        ),
    ]
