# Generated by Django 4.1.3 on 2022-11-15 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_hosp_double_alter_hosp_single_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital.hosp'),
        ),
        migrations.AlterField(
            model_name='hosp',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
