# Generated by Django 4.1.3 on 2022-11-15 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_rename_id_hosp_r_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosp',
            name='triple',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
